### ISSUE TITLE
make filter fields not case sensitive

### ISSUE THREAD

**Issue by sbma44** [propublica/sunlight-congress#468]
result=Passed works, result=passed doesn't. boo.

**Comment by ben-zen** [comment]
I was about to open a bug on this for another filter field, namely `history.enacted`. I was rather surprised by case sensitivity like that in a web API, especially since it makes using a few Python libraries much harder. In particular, I use requests to make API calls, and was wondering why the following wasn't working:
```python
import requests
headers = { 'X-APIKEY' : <Secret> }
parameters = { 'history.enacted' : True, 'congress' = 114, 'bill_type' : 'hr' }
call = requests.get("https://congress.api.sunlightfoundation.com/bills", headers=headers, params=parameters)
response = call.json()
call.url
# returns 'https://congress.api.sunlightfoundation.com/bills?history.enacted=True&congress=114&bill_type=hr'
response['count']
# returns 0
```
I was enlightened when I looked through the documentation and pondered for a moment, then tried this slight modification:
``` python
parameters['history.enacted'] = 'true'
call = requests.get("https://congress.api.sunlightfoundation.com/bills", headers=headers, params=parameters)
response = call.json()
call.url
# returns 'https://congress.api.sunlightfoundation.com/bills?history.enacted=true&congress=114&bill_type=hr'
response['count']
# returns 48
```
I'd normally consider a boolean case-insensitive, especially since this adds significant cognitive load to be able to use this API with Requests, since it transforms python objects into their standard string form before putting them in URL query strings. Is there any way the boolean fields can be handled in a case-insensitive fashion, even upon receiving the URL?
