### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by TheTFo** [propublica/sunlight-congress#535]
Sorry, I posted this issue last night under a different account, meant to do it from this one!

Attempting to call the health check endpoint from my browser client (localhost, development environment), and getting a CORS problem:

XMLHttpRequest cannot load https://congress.api.sunlightfoundation.com/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Code looks like:

$.get(https://congress.api.sunlightfoundation.com)

Using Chrome 54.0.2840.87.

I don't yet have an API key, as the page looks like it's down. This endpoint shouldn't require it, though. The doc also mentions all domains are allowed, so it should "Just Work". Is this something that's being addressed, or is it an issue on my end?

Looks like it's due to this commit:

https://github.com/propublica/congress/commit/99679be91086ce14bc73d4887c4787101314b05c

Thanks!

**Comment by TheTFo** [comment]
Hi 
Any update on this?

**Comment by amrsh** [comment]
+1: all calls to the api return a response with the header:

   access-control-allow-origin: http://localhost:9000

which prevents XMLHttpRequest from working.

**Comment by amrsh** [comment]
Actually it turns out that my issue was due to CloudFront caching the response based on IP address, which means that calls from a different hostname from the same IP fail (the response header has access-control-allow-origin set with the cached value). This manifested itself in our test setup, but could also occur e.g. if a user accessed two different sites using the api.

I worked around it by sending the hostname as a bogus param, which misses the cache since it is a different request. Ideally this would be fixed on the server side by setting up CloudFront to cache based on Origin as well as IP, which I believe is possible:

http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/header-caching.html#header-caching-web-selecting
